redis:
    image: redis
db:
    image: postgres:9.4
vote:
    image: debaduttapradhan1996/vote-app
    envirnment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
       - 5000:80
    link:
       - redis:redis
result:
    image: debaduttapradhan1996/result-app
    ports:
       - 5001:80
    link:
       - redis:redis
       - db:db
worker:
    image: debaduttapradhan1996/worker-app
    link:
       - redis:redis
       - db:db
